# Generated by Django 3.2.4 on 2021-06-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=10000)),
                ('src_image', models.CharField(max_length=10000)),
                ('ocr_text', models.CharField(max_length=10000)),
            ],
        ),
    ]
