# Generated by Django 3.2.4 on 2021-06-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='ocr_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='session_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='src_image',
            field=models.CharField(max_length=100),
        ),
    ]
